### PR TITLE
IHRACP-5834: Pypodcaster repo gha production codeartifact

### PR DESCRIPTION
**Pull request by poonamshinde-ihm**
## JIRA Ticket
- [IHRACP-5834](https://ihm-it.atlassian.net/browse/IHRACP-5834)

### CI/CD Workflow and Versioning Explanation
- CI/CD Pipeline Overview:

- This CI/CD workflow automates the deployment of the pypodcastparser-ihr Python package to AWS CodeArtifact. It dynamically determines the version based on the branch, using the latest release tag and commit count.
- When changes are pushed to any branch, the CI/CD pipeline is triggered, resulting in the creation of a new build/image/package on CodeArtifact. The naming convention for the development versions follows the format: `current_release_version.dev.<commit-number>`. Examples include `1.5.1.dev1`, `1.5.1.dev2`, and so on.
- and for master branch it will craete with lattest release tag `1.6.1`

#### Major Changes:
- Create CI/CD to automatically deploy to CodeArtifact

## How to test:
-  push any changes in any branch and check on CodeArtifact has created new build and expected result is below
`current_release_version.dev.<commit-id>`
 Examples:  `1.5.1.dev1`
- if your on master branch or relsesed new version then you will get `1.6.1`

## image which i have build on production AWS codeartifact via this automation process
https://us-east-1.console.aws.amazon.com/codesuite/codeartifact/d/219619990026/content-platform/r/content-platform/p/pypi/pypodcastparser-ihr/v/1.0.0.dev171?region=us-east-1

## image which i have build on stage AWS codeartifact via this automation process
https://us-east-1.console.aws.amazon.com/codesuite/codeartifact/d/827541288795/content-platform/r/content-platform/p/pypi/pypodcastparser-ihr/v/1.0.0.dev170?region=us-east-1

- workflow: 
https://github.com/iheartradio/pyPodcastParser/actions/runs/7192776825

[IHRACP-5834]: https://ihm-it.atlassian.net/browse/IHRACP-5834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by daleyp24 — CHANGES_REQUESTED** [review]
same comment as the podcast utils ci

**Comment by poonamshinde-ihm** [comment]
> same comment as the podcast utils ci

@daleyp24 @IanNoyes as per yesterdays discussion i have move this build to production which is `1.0.0.dev171` and attached build url on PR description. pip install pypodcastparser-ihr==1.0.0.dev171

whenever we deployed this branch to master then only it will create build 1.0.0

**Review by daleyp24 — CHANGES_REQUESTED** [review]
can you update the deploy script too. Also can you use the version from the settings.py or hardcode it. the current one is outdated

**Comment by KMichaelMcGaw** [comment]
I see that when we push to master it takes the current `tag` and makes that the version. Do we want this over something like https://github.com/iheartradio/episodeingestion/actions/workflows/push-released-version.yml where we create the tag while creating the new version?  Maybe I don't understand how the tag will be incremented.

**Comment by poonamshinde-ihm** [comment]
> I see that when we push to master it takes the current `tag` and makes that the version. Do we want this over something like https://github.com/iheartradio/episodeingestion/actions/workflows/push-released-version.yml where we create the tag while creating the new version? Maybe I don't understand how the tag will be incremented.

@KMichaelMcGaw  please read the PR description for this and if you. still have any questions then we can sync over a call.

**Review by KMichaelMcGaw — APPROVED** [review]

**Review by DrewJoseyGit — APPROVED** [review]

**Review by daleyp24 — APPROVED** [review]

**Pull request merged**
